using MeroBriksha.Core;
using MeroBriksha.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata.Ecma335;
using System.Text;
using System.Threading.Tasks;

namespace MeroBriksha.Services.Classes
{
    public class Plant : IPlant
    {
        List<MeroBriksha.Core.Plant> Plants = new List<MeroBriksha.Core.Plant>()
            {
                new Core.Plant { ID = "1", NAME = "Sal" },
                new Core.Plant { ID = "2", NAME = "Sissoo" },
                new Core.Plant { ID = "3", NAME = "Teak" },
                new Core.Plant { ID = "4", NAME = "Rhododendron" },
                new Core.Plant { ID = "5", NAME = "Chir Pine" },
                new Core.Plant { ID = "6", NAME = "Deodar" },
                new Core.Plant { ID = "7", NAME = "Silver Fir" },
                new Core.Plant { ID = "8", NAME = "Spruce" },
                new Core.Plant { ID = "9", NAME = "Himalayan Birch" },
                new Core.Plant { ID = "10", NAME = "Oak" },
                new Core.Plant { ID = "11", NAME = "Maple" },
                new Core.Plant { ID = "12", NAME = "Magnolia" },
                new Core.Plant { ID = "13", NAME = "Banyan" },
                new Core.Plant { ID = "14", NAME = "Peepal" },
                new Core.Plant { ID = "15", NAME = "Neem" },
                new Core.Plant { ID = "16", NAME = "Mango" },
                new Core.Plant { ID = "17", NAME = "Jackfruit" },
                new Core.Plant { ID = "18", NAME = "Bamboo" },
                new Core.Plant { ID = "19", NAME = "Banana" },
                new Core.Plant { ID = "20", NAME = "Lemon" },
                new Core.Plant { ID = "21", NAME = "Orange" },
                new Core.Plant { ID = "22", NAME = "Litchi" },
                new Core.Plant { ID = "23", NAME = "Guava" },
                new Core.Plant { ID = "24", NAME = "Custard Apple" },
                new Core.Plant { ID = "25", NAME = "Papaya" },
                new Core.Plant { ID = "26", NAME = "Pomegranate" },
                new Core.Plant { ID = "27", NAME = "Fig" },
                new Core.Plant { ID = "28", NAME = "Mulberry" },
                new Core.Plant { ID = "29", NAME = "Walnut" },
                new Core.Plant { ID = "30", NAME = "Chestnut" },
                new Core.Plant { ID = "31", NAME = "Alder" },
                new Core.Plant { ID = "32", NAME = "Poplar" },
                new Core.Plant { ID = "33", NAME = "Willow" },
                new Core.Plant { ID = "34", NAME = "Plum" },
                new Core.Plant { ID = "35", NAME = "Peach" },
                new Core.Plant { ID = "36", NAME = "Apricot" },
                new Core.Plant { ID = "37", NAME = "Apple" },
                new Core.Plant { ID = "38", NAME = "Pear" },
                new Core.Plant { ID = "39", NAME = "Cherry" },
                new Core.Plant { ID = "40", NAME = "Persimmon" },
                new Core.Plant { ID = "41", NAME = "Camphor" },
                new Core.Plant { ID = "42", NAME = "Cinnamon" },
                new Core.Plant { ID = "43", NAME = "Cardamom" },
                new Core.Plant { ID = "44", NAME = "Tea" },
                new Core.Plant { ID = "9", NAME = "Himalayan Birch" },
                new Core.Plant { ID = "10", NAME = "Oak" },
                new Core.Plant { ID = "11", NAME = "Maple" },
                new Core.Plant { ID = "12", NAME = "Magnolia" },
                new Core.Plant { ID = "13", NAME = "Banyan" },
                new Core.Plant { ID = "14", NAME = "Peepal" },
                new Core.Plant { ID = "15", NAME = "Neem" },
                new Core.Plant { ID = "16", NAME = "Mango" },
                new Core.Plant { ID = "17", NAME = "Jackfruit" },
                new Core.Plant { ID = "18", NAME = "Bamboo" },
                new Core.Plant { ID = "19", NAME = "Banana" },
                new Core.Plant { ID = "20", NAME = "Lemon" },
                new Core.Plant { ID = "21", NAME = "Orange" },
                new Core.Plant { ID = "22", NAME = "Litchi" },
                new Core.Plant { ID = "23", NAME = "Guava" },
                new Core.Plant { ID = "24", NAME = "Custard Apple" },
                new Core.Plant { ID = "25", NAME = "Papaya" },
                new Core.Plant { ID = "26", NAME = "Pomegranate" },
                new Core.Plant { ID = "27", NAME = "Fig" },
                new Core.Plant { ID = "28", NAME = "Mulberry" },
                new Core.Plant { ID = "29", NAME = "Walnut" },
                new Core.Plant { ID = "30", NAME = "Chestnut" },
                new Core.Plant { ID = "31", NAME = "Alder" },
                new Core.Plant { ID = "32", NAME = "Poplar" },
                new Core.Plant { ID = "33", NAME = "Willow" },
                new Core.Plant { ID = "34", NAME = "Plum" },
                new Core.Plant { ID = "35", NAME = "Peach" },
                new Core.Plant { ID = "36", NAME = "Apricot" },
                new Core.Plant { ID = "37", NAME = "Apple" },
                new Core.Plant { ID = "38", NAME = "Pear" },
                new Core.Plant { ID = "39", NAME = "Cherry" },
                new Core.Plant { ID = "40", NAME = "Persimmon" },
                new Core.Plant { ID = "41", NAME = "Camphor" },
                new Core.Plant { ID = "42", NAME = "Cinnamon" },
                new Core.Plant { ID = "43", NAME = "Cardamom" },
                new Core.Plant { ID = "44", NAME = "Tea" },
                new Core.Plant { ID = "45", NAME = "Coffee" },
                new Core.Plant { ID = "46", NAME = "Eucalyptus" },
                new Core.Plant { ID = "47", NAME = "Juniper" },
                new Core.Plant { ID = "48", NAME = "Horse Chestnut" },
                new Core.Plant { ID = "49", NAME = "Sugarcane" },
                new Core.Plant { ID = "50", NAME = "Rice" },
                new Core.Plant { ID = "51", NAME = "Wheat" },
                new Core.Plant { ID = "52", NAME = "Maize" },
                new Core.Plant { ID = "53", NAME = "Barley" },
                new Core.Plant { ID = "54", NAME = "Millet" },
                new Core.Plant { ID = "55", NAME = "Buckwheat" },
                new Core.Plant { ID = "56", NAME = "Sorghum" },
                new Core.Plant { ID = "57", NAME = "Lentil" },
                new Core.Plant { ID = "9", NAME = "Himalayan Birch" },
                new Core.Plant { ID = "10", NAME = "Oak" },
                new Core.Plant { ID = "11", NAME = "Maple" },
                new Core.Plant { ID = "12", NAME = "Magnolia" },
                new Core.Plant { ID = "13", NAME = "Banyan" },
                new Core.Plant { ID = "14", NAME = "Peepal" },
                new Core.Plant { ID = "15", NAME = "Neem" },
                new Core.Plant { ID = "16", NAME = "Mango" },
                new Core.Plant { ID = "17", NAME = "Jackfruit" },
                new Core.Plant { ID = "18", NAME = "Bamboo" },
                new Core.Plant { ID = "19", NAME = "Banana" },
                new Core.Plant { ID = "20", NAME = "Lemon" },
                new Core.Plant { ID = "21", NAME = "Orange" },
                new Core.Plant { ID = "22", NAME = "Litchi" },
                new Core.Plant { ID = "23", NAME = "Guava" },
                new Core.Plant { ID = "24", NAME = "Custard Apple" },
                new Core.Plant { ID = "25", NAME = "Papaya" },
                new Core.Plant { ID = "26", NAME = "Pomegranate" },
                new Core.Plant { ID = "27", NAME = "Fig" },
                new Core.Plant { ID = "28", NAME = "Mulberry" },
                new Core.Plant { ID = "29", NAME = "Walnut" },
                new Core.Plant { ID = "30", NAME = "Chestnut" },
                new Core.Plant { ID = "31", NAME = "Alder" },
                new Core.Plant { ID = "32", NAME = "Poplar" },
                new Core.Plant { ID = "33", NAME = "Willow" },
                new Core.Plant { ID = "34", NAME = "Plum" },
                new Core.Plant { ID = "35", NAME = "Peach" },
                new Core.Plant { ID = "36", NAME = "Apricot" },
                new Core.Plant { ID = "37", NAME = "Apple" },
                new Core.Plant { ID = "38", NAME = "Pear" },
                new Core.Plant { ID = "39", NAME = "Cherry" },
                new Core.Plant { ID = "40", NAME = "Persimmon" },
                new Core.Plant { ID = "41", NAME = "Camphor" },
                new Core.Plant { ID = "42", NAME = "Cinnamon" },
                new Core.Plant { ID = "43", NAME = "Cardamom" },
                new Core.Plant { ID = "44", NAME = "Tea" },
                new Core.Plant { ID = "45", NAME = "Coffee" },
                new Core.Plant { ID = "46", NAME = "Eucalyptus" },
                new Core.Plant { ID = "47", NAME = "Juniper" },
                new Core.Plant { ID = "48", NAME = "Horse Chestnut" },
                new Core.Plant { ID = "49", NAME = "Sugarcane" },
                new Core.Plant { ID = "50", NAME = "Rice" },
                new Core.Plant { ID = "51", NAME = "Wheat" },
                new Core.Plant { ID = "52", NAME = "Maize" },
                new Core.Plant { ID = "53", NAME = "Barley" },
                new Core.Plant { ID = "54", NAME = "Millet" },
                new Core.Plant { ID = "55", NAME = "Buckwheat" },
                new Core.Plant { ID = "56", NAME = "Sorghum" },
                new Core.Plant { ID = "57", NAME = "Lentil" },
                new Core.Plant { ID = "58", NAME = "Chickpea" },
                new Core.Plant { ID = "59", NAME = "Potato" },
                new Core.Plant { ID = "60", NAME = "Tomato" },
                new Core.Plant { ID = "9", NAME = "Fir" },
                new Core.Plant { ID = "10", NAME = "Cherry Blossom" },
                new Core.Plant { ID = "11", NAME = "Magnolia" },
                new Core.Plant { ID = "12", NAME = "Palm" },
                new Core.Plant { ID = "13", NAME = "Olive" },
                new Core.Plant { ID = "14", NAME = "Banyan" },
                new Core.Plant { ID = "15", NAME = "Fig" },
                new Core.Plant { ID = "16", NAME = "Eucalyptus" },
                new Core.Plant { ID = "17", NAME = "Juniper" },
                new Core.Plant { ID = "18", NAME = "Poplar" },
                new Core.Plant { ID = "19", NAME = "Chestnut" },
                new Core.Plant { ID = "20", NAME = "Dogwood" }
            };
        public List<string> GetALlPlantNames()
        {
            var PlantNames = Plants
            .Select(x => x.NAME)
            .ToList();

            return PlantNames;
        }

        public string GetPlantNameById(string plantId)
        {


            var plant = Plants.FirstOrDefault(p => p.ID == plantId);
            return plant != null ? plant.NAME : null;
        }
    }
}
