// <auto-generated />
using System;
using MeroBriksha.Data.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeroBriksha.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610194007_AddTreeAssignments")]
    partial class AddTreeAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeroBriksha.Core.Entities.Campaign", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CREATEDDATE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DESCRIPTION")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ENDDATEUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ORGANIZERNAME")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("STARTDATEUTC")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TARGETTREECOUNT")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Campaigns", (string)null);
                });

            modelBuilder.Entity("MeroBriksha.Core.Entities.Donation", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ID");

                    b.Property<decimal>("AMOUNT")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AMOUNT");

                    b.Property<string>("CAMPAIGNID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CAMPAIGNID");

                    b.Property<DateTime>("CREATEDDATE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATEDDATE")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DONORID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DONORID");

                    b.Property<string>("PAYMENTREFERENCE")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PAYMENTREFERENCE");

                    b.Property<string>("REMARKS")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("REMARKS");

                    b.Property<int>("STATUS")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<DateTime?>("VERIFIEDDATE")
                        .HasColumnType("datetime2")
                        .HasColumnName("VERIFIEDDATE");

                    b.HasKey("ID");

                    b.HasIndex("CAMPAIGNID");

                    b.HasIndex("DONORID");

                    b.ToTable("Donations", (string)null);
                });

            modelBuilder.Entity("MeroBriksha.Core.Entities.Donor", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ADDRESS")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CREATEDDATE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EMAIL")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FULLNAME")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PHONENUMBER")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Donors", (string)null);
                });

            modelBuilder.Entity("MeroBriksha.Core.Entities.Plant", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DESCRIPTION")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SCIENTIFICNAME")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID");

                    b.ToTable("Plants", (string)null);
                });

            modelBuilder.Entity("MeroBriksha.Core.Entities.TreeAssignment", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CREATEDDATE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATEDDATE")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DONATIONID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DONATIONID");

                    b.Property<string>("REMARKS")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("REMARKS");

                    b.Property<int>("STATUS")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.HasKey("ID");

                    b.HasIndex("DONATIONID");

                    b.ToTable("TreeAssignments", (string)null);
                });

            modelBuilder.Entity("MeroBriksha.Core.Entities.Donation", b =>
                {
                    b.HasOne("MeroBriksha.Core.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CAMPAIGNID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeroBriksha.Core.Entities.Donor", "Donor")
                        .WithMany()
                        .HasForeignKey("DONORID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("MeroBriksha.Core.Entities.TreeAssignment", b =>
                {
                    b.HasOne("MeroBriksha.Core.Entities.Donation", "Donation")
                        .WithMany()
                        .HasForeignKey("DONATIONID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donation");
                });
#pragma warning restore 612, 618
        }
    }
}
