// <auto-generated />
using System;
using MeroBriksha.Data.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeroBriksha.Data.Migrations.postgre
{
    [DbContext(typeof(PostgreSqlDbContext))]
    [Migration("20260815214835_FirstPostgre")]
    partial class FirstPostgre
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeroBriksha.Core.Entities.Campaign", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CREATEDDATE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DESCRIPTION")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ENDDATEUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ISDELETED")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ORGANIZERNAME")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("STARTDATEUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TARGETTREECOUNT")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Campaigns", (string)null);
                });

            modelBuilder.Entity("MeroBriksha.Core.Entities.Donation", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ID");

                    b.Property<decimal>("AMOUNT")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AMOUNT");

                    b.Property<string>("CAMPAIGNID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CAMPAIGNID");

                    b.Property<DateTime>("CREATEDDATE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATEDDATE");

                    b.Property<string>("DONORID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DONORID");

                    b.Property<string>("PAYMENTREFERENCE")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PAYMENTREFERENCE");

                    b.Property<string>("REMARKS")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("REMARKS");

                    b.Property<int>("STATUS")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS");

                    b.Property<DateTime?>("VERIFIEDDATE")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VERIFIEDDATE");

                    b.HasKey("ID");

                    b.HasIndex("CAMPAIGNID");

                    b.HasIndex("DONORID");

                    b.ToTable("Donations", (string)null);
                });

            modelBuilder.Entity("MeroBriksha.Core.Entities.Donor", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ADDRESS")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CREATEDDATE")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EMAIL")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FULLNAME")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PHONENUMBER")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("ID");

                    b.ToTable("Donors", (string)null);
                });

            modelBuilder.Entity("MeroBriksha.Core.Entities.Plant", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DESCRIPTION")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SCIENTIFICNAME")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SPECIES")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID");

                    b.ToTable("Plants", (string)null);
                });

            modelBuilder.Entity("MeroBriksha.Core.Entities.Tree", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ID");

                    b.Property<string>("ADDRESS")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ADDRESS");

                    b.Property<DateTime>("CREATEDDATE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATEDDATE");

                    b.Property<decimal?>("LATITUDE")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("LATITUDE");

                    b.Property<string>("LOCATIONLINK")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("LOCATIONLINK");

                    b.Property<decimal?>("LONGITUDE")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("LONGITUDE");

                    b.Property<DateTime>("PLANTEDDATE")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PLANTEDDATE");

                    b.Property<string>("PLANTID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PLANTID");

                    b.Property<int>("STATUS")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS");

                    b.Property<string>("TRACKINGCODE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TRACKINGCODE");

                    b.Property<string>("TREEASSIGNMENTID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TREEASSIGNMENTID");

                    b.HasKey("ID");

                    b.HasIndex("PLANTID");

                    b.HasIndex("TRACKINGCODE")
                        .IsUnique();

                    b.HasIndex("TREEASSIGNMENTID")
                        .IsUnique();

                    b.ToTable("Trees", (string)null);
                });

            modelBuilder.Entity("MeroBriksha.Core.Entities.TreeAssignment", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CREATEDDATE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CREATEDDATE");

                    b.Property<string>("DONATIONID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DONATIONID");

                    b.Property<string>("REMARKS")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("REMARKS");

                    b.Property<int>("STATUS")
                        .HasColumnType("integer")
                        .HasColumnName("STATUS");

                    b.HasKey("ID");

                    b.HasIndex("DONATIONID");

                    b.ToTable("TreeAssignments", (string)null);
                });

            modelBuilder.Entity("MeroBriksha.Core.Entities.Donation", b =>
                {
                    b.HasOne("MeroBriksha.Core.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CAMPAIGNID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeroBriksha.Core.Entities.Donor", "Donor")
                        .WithMany()
                        .HasForeignKey("DONORID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("MeroBriksha.Core.Entities.Tree", b =>
                {
                    b.HasOne("MeroBriksha.Core.Entities.Plant", null)
                        .WithMany()
                        .HasForeignKey("PLANTID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MeroBriksha.Core.Entities.TreeAssignment", "TreeAssignment")
                        .WithOne()
                        .HasForeignKey("MeroBriksha.Core.Entities.Tree", "TREEASSIGNMENTID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TreeAssignment");
                });

            modelBuilder.Entity("MeroBriksha.Core.Entities.TreeAssignment", b =>
                {
                    b.HasOne("MeroBriksha.Core.Entities.Donation", "Donation")
                        .WithMany()
                        .HasForeignKey("DONATIONID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donation");
                });
#pragma warning restore 612, 618
        }
    }
}
